"""Create deterministic, synthetic teaching fixtures; no patient data or dependencies."""
import argparse
from pathlib import Path
import random


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path, help="New directory; must not already exist")
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=False)
    rng = random.Random(20260913)
    n = 6000
    frequencies = [rng.uniform(0.15, 0.45) for _ in range(n)]
    rows = []
    for s in range(40):
        row = []
        for j, p in enumerate(frequencies):
            pair = ["G" if rng.random() < p else "A" for _ in range(2)]
            if s == 2 and j < 150:
                pair = ["A", "A"]
            if (s == 39 and j % 3 == 0) or (j == 0 and s < 10):
                pair = ["0", "0"]
            row.extend(pair)
        rows.append(row)
    rows[1] = rows[0].copy()
    with (args.output / "array.map").open("w") as handle:
        for j in range(n):
            handle.write(f"{j // 1000 + 1}\tv{j+1}\t0\t{(j % 1000 + 1)*10000}\n")
    with (args.output / "array.ped").open("w") as handle:
        for s, row in enumerate(rows):
            handle.write(f"F{s+1:02d} S{s+1:02d} 0 0 {s%2+1} -9 " + " ".join(row) + "\n")
    with (args.output / "intensity.csv").open("w") as handle:
        handle.write("scenario,probe,BAF,LRR\n")
        for scenario, bands, lrr in [
            ("normal", [0, .5, 1], 0), ("deletion", [0, 1], -.6),
            ("duplication", [0, 1/3, 2/3, 1], .3), ("ROH", [0, 1], 0)
        ]:
            for j in range(12):
                handle.write(f"{scenario},{j+1},{bands[j % len(bands)]:.3f},{lrr}\n")
    # This SAM is pre-aligned by construction, not generated by an aligner.
    reference = "".join(rng.choice("ACGT") for _ in range(2000))
    alt = next(b for b in "ACGT" if b != reference[999])
    (args.output / "reference.fa").write_text(">chrToy\n" + reference + "\n")
    with (args.output / "reads.fastq").open("w") as fastq, (args.output / "aligned.sam").open("w") as sam:
        sam.write("@HD\tVN:1.6\tSO:unsorted\n@SQ\tSN:chrToy\tLN:2000\n@RG\tID:toy\tSM:sample01\tPL:ILLUMINA\n")
        for i in range(40):
            start = 901 + i
            seq = list(reference[start-1:start-1+150])
            if i % 2:
                seq[1000-start] = alt
            seq = "".join(seq)
            quality = "I" * len(seq)
            fastq.write(f"@read{i+1}\n{seq}\n+\n{quality}\n")
            sam.write(f"read{i+1}\t0\tchrToy\t{start}\t60\t150M\t*\t0\t0\t{seq}\t{quality}\tRG:Z:toy\n")
    header = '''##fileformat=VCFv4.2
##contig=<ID=chrToy,length=2000>
##FILTER=<ID=LowDP,Description="Teaching depth flag">
##FILTER=<ID=LowMQ,Description="Teaching mapping quality flag">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read depth">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype quality">
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tsample01
'''
    examples = [(1000, "PASS", "0/1:20,20:40:99"),
                (1100, "LowDP", "0/1:2,1:3:8"),
                (1200, "PASS", "0/1:38,2:40:15"),
                (1300, "LowMQ", "0/1:19,21:40:10")]
    with (args.output / "review.vcf").open("w") as handle:
        handle.write(header)
        for pos, flag, sample in examples:
            ref = reference[pos-1]
            variant = next(b for b in "ACGT" if b != ref)
            handle.write(f"chrToy\t{pos}\t.\t{ref}\t{variant}\t60\t{flag}\t.\tGT:AD:DP:GQ\t{sample}\n")
    print(f"Created {args.output}: 40 samples, 6000 SNPs; expected SNV chrToy:1000 {reference[999]}>{alt}")


if __name__ == "__main__":
    main()
